spring.application.name=app

spring.jpa.hibernate.ddl-auto=validate

# Actuator
management.server.port=8081
management.endpoints.web.exposure.include=health,info
info.app.git-sha=${APP_GIT_SHA:unknown}

management.info.env.enabled=true